name: workout_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  design_system:
    path: ../../packages/design_system
  authentication:
    path: ../../packages/authentication
  supabase_flutter: ^2.0.0
  provider: ^6.1.2
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
